### ISSUE TITLE
SESSION_COOKIE_HTTPONLY

### ISSUE THREAD

**Issue by TMFRook** [rasoolsomji/django-security#2]
Great resource, but what about the following:

* SESSION_COOKIE_HTTPONLY
* CSRF_COOKIE_HTTPONLY

**Comment by rasoolsomji** [comment]
Good spot! I think I initially thought that CSRF_COOKIE_HTTPONLY was too minor to bother with (since, as the Django documentation itself states, if an attacker can access your cookies, you are in a lot more trouble anyway) but I do have CSRF_USE_SESSIONS which is equally minor so I probably should add CSRF_COOKIE_HTTPONLY.

As for SESSION_COOKIE_HTTPONLY the default is already True and again, as the documentation states, it is rarely a good idea to turn it off. At the moment all the items in this repo are for active actions someone could take to secure their project, but I was thinking I could maybe have an additional section of 'Good defaults that one should be wary of disabling' to cover items like this.

Thanks for the feedback!
